server:
  port: 8080
spring:
  application:
    name: web-01
  datasource:
    url: jdbc:mysql://localhost:3306/monodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 985263
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
